import products1 from "../assets/product-01.jpg";
import products2 from "../assets/product-02.jpg";
import products3 from "../assets/product-03.jpg";
import products4 from "../assets/product-04.jpg";
import products5 from "../assets/product-05.jpg";
import products6 from "../assets/product-06.jpg";
import products7 from "../assets/product-07.jpg";
import products8 from "../assets/product-08.jpg";
import products9 from "../assets/product-09.jpg";
import products10 from "../assets/product-10.jpg";
import products11 from "../assets/product-11.jpg";
import products12 from "../assets/product-12.jpg";
import products13 from "../assets/product-13.jpg";
import products14 from "../assets/product-14.jpg";
import products15 from "../assets/product-15.jpg";
import products16 from "../assets/product-16.jpg";

const productsData = [
  {
    id: 1,
    image: products1,
    name: "Esprit Ruffle Shirt",
    price: "$16.64",
    category: "female",
    stock: 1,
    description: "A trendy ruffle shirt perfect for casual wear. Soft and breathable fabric for all-day comfort.",
    rating: 4.2,
    reviewsCount: 56,
    features: ["Lightweight", "Soft fabric", "Available in multiple sizes"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["Red", "Blue", "White"],
  },
  {
    id: 2,
    image: products2,
    name: "Nike Air Max",
    price: "$120.00",
    category: "female",
    stock: 11,
    description: "The iconic Nike Air Max with superior cushioning and support for all-day comfort.",
    rating: 4.8,
    reviewsCount: 234,
    features: ["Air-cushioned sole", "Durable upper material", "Available in multiple colors"],
    availability: "In Stock",
    discount: "15% off",
    colorVariants: ["Black", "White", "Pink"],
  },
  {
    id: 3,
    image: products3,
    name: "Adidas Running Shoes",
    price: "$89.99",
    category: "male",
    stock: 8,
    description: "High-performance running shoes designed for stability and comfort during long runs.",
    rating: 4.5,
    reviewsCount: 120,
    features: ["Breathable mesh", "Lightweight", "Supportive sole"],
    availability: "In Stock",
    discount: "20% off",
    colorVariants: ["Black", "Blue", "Green"],
  },
  {
    id: 4,
    image: products4,
    name: "Puma Backpack",
    price: "$45.00",
    category: "female",
    stock: 0,
    description: "Stylish and functional backpack with multiple compartments for organized storage.",
    rating: 4.0,
    reviewsCount: 30,
    features: ["Durable material", "Multiple pockets", "Water-resistant"],
    availability: "Out of Stock",
    discount: "5% off",
    colorVariants: ["Black", "Grey", "Red"],
  },
  {
    id: 5,
    image: products5,
    name: "Reebok Jacket",
    price: "$75.00",
    category: "female",
    stock: 18,
    description: "Warm and comfortable jacket perfect for outdoor activities in cold weather.",
    rating: 4.3,
    reviewsCount: 85,
    features: ["Windproof", "Fleece-lined", "Adjustable hood"],
    availability: "In Stock",
    discount: "25% off",
    colorVariants: ["Blue", "Green", "Grey"],
  },
  {
    id: 6,
    image: products6,
    name: "Under Armour Shorts",
    price: "$30.00",
    category: "watch",
    stock: 5,
    description: "Lightweight athletic shorts for maximum mobility during workouts.",
    rating: 4.7,
    reviewsCount: 190,
    features: ["Breathable fabric", "Quick-dry", "Elastic waistband"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["Black", "Navy", "Grey"],
  },
  {
    id: 7,
    image: products7,
    name: "New Balance Sneakers",
    price: "$110.00",
    category: "female",
    stock: 6,
    description: "Comfortable sneakers for casual wear or light workouts, with superior arch support.",
    rating: 4.6,
    reviewsCount: 155,
    features: ["Comfort fit", "Durable rubber sole", "Stylish design"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["White", "Blue", "Pink"],
  },
  {
    id: 8,
    image: products8,
    name: "Asics Gel-Lyte",
    price: "$100.00",
    category: "female",
    stock: 20,
    description: "Asics Gel-Lyte with GEL cushioning for enhanced comfort and shock absorption.",
    rating: 4.9,
    reviewsCount: 270,
    features: ["Gel cushioning", "Breathable upper", "Flexible sole"],
    availability: "In Stock",
    discount: "30% off",
    colorVariants: ["Black", "White", "Orange"],
  },
  {
    id: 9,
    image: products9,
    name: "Converse Chuck Taylor",
    price: "$65.00",
    category: "shoe",
    stock: 11,
    description: "Classic Converse Chuck Taylor sneakers, versatile for any casual occasion.",
    rating: 4.7,
    reviewsCount: 200,
    features: ["Iconic design", "Durable canvas", "Rubber sole"],
    availability: "In Stock",
    discount: "5% off",
    colorVariants: ["Black", "White", "Red"],
  },
  {
    id: 10,
    image: products10,
    name: "Vans Old Skool",
    price: "$60.00",
    category: "female",
    stock: 8,
    description: "Vans Old Skool sneakers with signature side stripe and durable construction.",
    rating: 4.5,
    reviewsCount: 180,
    features: ["Suede and canvas upper", "Padded collar", "Vulcanized sole"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["Black", "White", "Blue"],
  },
  {
    id: 11,
    image: products11,
    name: "North Face Hoodie",
    price: "$90.00",
    category: "male",
    stock: 2,
    description: "North Face hoodie for warmth and comfort during outdoor activities.",
    rating: 4.8,
    reviewsCount: 240,
    features: ["Fleece-lined", "Adjustable hood", "Pockets"],
    availability: "In Stock",
    discount: "20% off",
    colorVariants: ["Grey", "Black", "Navy"],
  },
  {
    id: 12,
    image: products12,
    name: "Columbia Jacket",
    price: "$100.00",
    category: "belt",
    stock: 3,
    description: "Columbia jacket designed for outdoor adventurers, with weather-resistant fabric.",
    rating: 4.4,
    reviewsCount: 95,
    features: ["Water-resistant", "Lightweight", "Packable"],
    availability: "In Stock",
    discount: "15% off",
    colorVariants: ["Green", "Black", "Grey"],
  },
  {
    id: 13,
    image: products13,
    name: "Champion Sweatshirt",
    price: "$40.00",
    category: "female",
    stock: 18,
    description: "Champion sweatshirt for comfort and style, perfect for casual wear.",
    rating: 4.2,
    reviewsCount: 110,
    features: ["Soft fabric", "Ribbed cuffs", "Classic logo"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["Grey", "Black", "Red"],
  },
  {
    id: 14,
    image: products14,
    name: "Fila Sneakers",
    price: "$85.00",
    category: "female",
    stock: 15,
    description: "Fila sneakers with cushioned sole for superior comfort and a sleek design.",
    rating: 4.5,
    reviewsCount: 160,
    features: ["Comfort fit", "Durable material", "Stylish"],
    availability: "In Stock",
    discount: "10% off",
    colorVariants: ["White", "Blue", "Pink"],
  },
  {
    id: 15,
    image: products15,
    name: "Timberland Boots",
    price: "$120.00",
    category: "watch",
    stock: 15,
    description: "Timberland boots with waterproof construction and rugged durability.",
    rating: 4.9,
    reviewsCount: 300,
    features: ["Waterproof", "Premium leather", "Grip sole"],
    availability: "In Stock",
    discount: "15% off",
    colorVariants: ["Brown", "Black"],
  },
  {
    id: 16,
    image: products16,
    name: "Dr. Martens Boots",
    price: "$150.00",
    category: "female",
    stock: 1,
    description: "Classic Dr. Martens boots with durable leather and signature air-cushioned sole.",
    rating: 4.8,
    reviewsCount: 280,
    features: ["Air-cushioned sole", "Durable leather", "Timeless design"],
    availability: "In Stock",
    discount: "20% off",
    colorVariants: ["Black", "Brown"],
  },
];

export default productsData;

